// Menu
export const  ON_MENU_SELECTION_CLICK='ON_MENU_SELECTION_CLICK';

// Orders
export const ON_ACTIVE_TABLE_CHANGE='ON_ACTIVE_TABLE_CHANGE';
export const ON_ORDER_ADD='ON_ORDER_ADD';
export const ON_CHECK_OUT_CLICK='ON_CHECK_OUT_CLICK';

// Settings
export const ON_ADD_SPECIAL_INPUT='ON_ADD_SPECIAL_INPUT';
export const ON_ADD_SPECIAL_SUBMIT='ON_ADD_SPECIAL_SUBMIT';